
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comilla = 14;
  public static final int cadena = 24;
  public static final int decimal = 22;
  public static final int coma = 10;
  public static final int flecha = 28;
  public static final int salto = 20;
  public static final int conj = 27;
  public static final int separador = 19;
  public static final int comillas = 13;
  public static final int corchete2 = 5;
  public static final int corchete1 = 4;
  public static final int guion = 16;
  public static final int punto = 9;
  public static final int gbajo = 15;
  public static final int EOF = 0;
  public static final int comlinea = 26;
  public static final int puntocoma = 8;
  public static final int palabra = 23;
  public static final int error = 1;
  public static final int barra = 12;
  public static final int comentario = 25;
  public static final int entero = 21;
  public static final int virgula = 7;
  public static final int asterisco = 11;
  public static final int interrogacion = 18;
  public static final int mas = 17;
  public static final int separacion = 29;
  public static final int llave2 = 3;
  public static final int llave1 = 2;
  public static final int dospuntos = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llave1",
  "llave2",
  "corchete1",
  "corchete2",
  "dospuntos",
  "virgula",
  "puntocoma",
  "punto",
  "coma",
  "asterisco",
  "barra",
  "comillas",
  "comilla",
  "gbajo",
  "guion",
  "mas",
  "interrogacion",
  "separador",
  "salto",
  "entero",
  "decimal",
  "palabra",
  "cadena",
  "comentario",
  "comlinea",
  "conj",
  "flecha",
  "separacion"
  };
}

