
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int mayorq = 16;
  public static final int comilla = 11;
  public static final int cadena = 24;
  public static final int casomin = 22;
  public static final int coma = 7;
  public static final int invertida = 18;
  public static final int separador = 17;
  public static final int conj = 14;
  public static final int comillas = 10;
  public static final int casosim = 25;
  public static final int guion = 15;
  public static final int punto = 6;
  public static final int EOF = 0;
  public static final int id = 20;
  public static final int puntocoma = 5;
  public static final int palabra = 19;
  public static final int error = 1;
  public static final int barra = 9;
  public static final int casomayus = 23;
  public static final int casonum = 21;
  public static final int asterisco = 8;
  public static final int mas = 12;
  public static final int interrogacion = 13;
  public static final int llave2 = 3;
  public static final int llave1 = 2;
  public static final int dospuntos = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llave1",
  "llave2",
  "dospuntos",
  "puntocoma",
  "punto",
  "coma",
  "asterisco",
  "barra",
  "comillas",
  "comilla",
  "mas",
  "interrogacion",
  "conj",
  "guion",
  "mayorq",
  "separador",
  "invertida",
  "palabra",
  "id",
  "casonum",
  "casomin",
  "casomayus",
  "cadena",
  "casosim"
  };
}

